name: Deploy Web App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run test
      run: |
        pip install pytest
        pytest tests/

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ec2-user
        KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "$KEY" > webapp.pem
        chmod 600 webapp.pem
        scp -o StrictHostKeyChecking=no -i webapp.pem index.html $USER@$HOST:/tmp/index.html
        ssh -o StrictHostKeyChecking=no -i webapp.pem $USER@$HOST "sudo mv /tmp/index.html /usr/share/nginx/html/index.html && sudo systemctl restart nginx"
